name: Pages

on: [push]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  HTML5:
    concurrency: ci-${{ github.ref }}

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      - name: Setup Dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib git lime https://github.com/openfl/lime --quiet
          haxelib git openfl https://github.com/openfl/openfl --quiet
          haxelib git flixel https://github.com/HaxeFlixel/flixel --quiet
        shell: cmd
      - name: Build
        run: |
          haxelib run lime build html5 -debug
        shell: cmd
      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: bin/html5/bin